routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'IndexController@index')->name('home'); // Главная
Route::get('news', 'NewsController@index')->name('news.index'); // Все новости
Route::get('news/{news}', 'NewsController@show')->name('news.show'); // Просмотр новости
Route::get('gallery', 'GalleryController@index')->name('gallery'); // Галерея

Route::resources([
    'admin-news' => 'Admin\NewsController', // Редактирование новостей
    'admin-gallery' => 'Admin\GalleryController', // Редактирование галереи
]);
Route::get('admin-options', 'Admin\OptionsController@edit')->name('admin-options'); // Настройка главной станицы
Route::post('admin-options', 'Admin\OptionsController@update');

app/Models/News.php
<?php
/**
 * Created by PhpStorm.
 * User: deida
 * Date: 27.08.2018
 * Time: 3:42
 */

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * Class News
 * @property int $id
 * @property string $title
 * @property string description
 * @property string content
 * @package App\Models
 */
class News extends Model
{
    protected $table = 'news';

    static $rules = [
        'title' => 'required|max:255',
        'description' => 'required|max:255',
        'content' => 'required',
        ];
}

app/Http/Controllers/Admin/NewsController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Models\News;
use Illuminate\Http\Request;

class NewsController extends AdminController
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('admin.news.index', ['posts' => News::orderBy('created_at', 'desc')->get()]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.news.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, News::$rules);

        $post = New News();
        $post->title = $request->input('title');
        $post->description = $request->input('description');
        $post->content = $request->input('content');
        $post->save();
        return redirect()->route('admin-news.edit', $post->id);
    }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $post = News::find($id);

        if (!$post) {
            abort(404);
        }

        return view('admin.news.edit', ['post' => $post]);
    }


    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, News::$rules);

        $post = News::find($id);
        $post->title = $request->input('title');
        $post->description = $request->input('description');
        $post->content = $request->input('content');
        $post->save();
        return redirect()->route('admin-news.edit', $post->id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        News::destroy($id);

        return redirect()->route('admin-news.index');
    }
}

app/Http/Controllers/NewsController.php
<?php

namespace App\Http\Controllers;

use App\Models\News;

class NewsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = [
            'posts' => News::orderBy('created_at', 'desc')->get(),
        ];

        return view('news.index', $data);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $data = [
            'post' => News::find($id),
        ];

        return view('news.show', $data);
    }

}

resources/views/admin/news/create.blade.php
@extends('layouts.admin')

@section('title', 'Новости')

@section('content')
    <fieldset class="m-2">
        {!! Form::open(['route' => 'admin-news.store'])!!}
            <a href="{{route('admin-news.index')}}">Назад</a>
            <div class="form-group">
                {{ Form::label('title', 'Заголовок') }}
                {{ Form::text('title', null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::label('description', 'Описание') }}
                {{ Form::text('description', null, ['class' => 'form-control']) }}
            </div>
            <div class="form-group">
                {{ Form::label('content', 'Контент') }}
                {{ Form::textArea('content', null, ['class' => 'form-control']) }}
            </div>
            {{ Form::submit('Сохранить', ['class' => 'btn btn-primary']) }}
        {!! Form::close() !!}
    </fieldset>
@endsection

resources/views/admin/news/edit.blade.php
@extends('layouts.admin')

@section('title', 'Новости')

@section('content')
    <fieldset class="m-2">
        <a href="{{route('admin-news.index')}}">Назад</a>
        {{ Form::model($post, ['route' => ['admin-news.update', $post->id], 'method' => 'PUT']) }}
        <div class="form-group">
            {{ Form::label('title', 'Заголовок') }}
            {{ Form::text('title', null, ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('description', 'Описание') }}
            {{ Form::text('description', null, ['class' => 'form-control']) }}
        </div>
        <div class="form-group">
            {{ Form::label('content', 'Контент') }}
            {{ Form::textArea('content', null, ['class' => 'form-control']) }}
        </div>
        <div class="float-left">
            {{ Form::submit('Сохранить', ['class' => 'btn btn-primary']) }}
        </div>
        {{ Form::close() }}

        {{ Form::open(['route' => ['admin-news.destroy', $post->id], 'method' => 'DELETE']) }}
        <div class="float-right">
            {{ Form::submit('Удалить', ['class' => 'btn btn-danger']) }}
        </div>
        {{ Form::close() }}
    </fieldset>
@endsection

resources/views/admin/news/index.blade.php
@extends('layouts.admin')

@section('title', 'Новости')

@section('content')
    <div class="m-2">
        <a href="{{ route('admin-news.create') }}" class="btn btn-primary">Создать новость</a>
    </div>
    <table class="table news-table">
        <thead>
        <tr>
            <td class="ids">#</td>
            <td>Заголовок</td>
            <td class="date">Дата</td>
        </tr>
        </thead>
        <tbody>
        @foreach($posts as $post)
            <tr>
                <td>{{ $post->id }}</td>
                <td><a href="{{ route('admin-news.edit', $post->id) }}">{{ $post->title }}</a></td>
                <td>{{ $post->created_at }}</td>
            </tr>
        @endforeach
        </tbody>
    </table>
@endsection